# Generated by Django 3.2 on 2021-05-02 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Способ реализации')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название тактики')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True, verbose_name='Описание тактики')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Technics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название техники')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.FloatField(verbose_name='Номер техники')),
                ('description', models.TextField(null=True, verbose_name='Описание техники')),
                ('tactics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technics', to='mainapp.tactics', verbose_name='Тактика')),
            ],
        ),
    ]
