# Generated by Django 3.2 on 2021-04-24 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='tactics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactics', to='mainapp.tactics', verbose_name='Категория'),
        ),
    ]
