# Generated by Django 3.2 on 2021-05-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_threat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер угрозы'),
        ),
    ]
