# Generated by Django 3.2 on 2021-04-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_technics_tactics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
