# Generated by Django 3.2 on 2021-04-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_implementation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technics',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Номер техники'),
        ),
        migrations.AlterField(
            model_name='technics',
            name='tactics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technics', to='mainapp.tactics', verbose_name='Тактика'),
        ),
    ]
